version: '3'

services:
  db:
    image: mariadb:10.5.4
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_PASSWORD=1
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    expose:
      - "3306"
    volumes:
      - /docker/mariadb:/var/lib/mysql

  nextcloud:
    image: nextcloud:18.0.6
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /docker/nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=root
      - NEXTCLOUD_ADMIN_PASSWORD=1
    restart: always
    depends_on:
      - db